name = "SESSION NAME" # used as prefix
path = "PATH/TO/OUTPUT/DIR"
sample_rate = 13 # seconds

[destinations]
[destinations.postgres]
database = ""
host = "127.0.0.1"
port = 5432
# Set username and password with envars

[destinations.redis]
database = 3
host = "127.0.0.1"
port = 6379

[sources]
[sources.fswebcam]
device = ""
input = ""
resolution = ""
format = ""
quality = ""
# optional
timestamp = true # Boolean
font = "" # must be supported by system
font_size = 12
data_banner = true # adds sensor readings to image

# [sources.scd30]